[window]
# padding = { x = 8, y = 8 }
opacity = 0.95
dynamic_title = true

[font]
size = 13.0

[font.offset]
x = 0
y = 6

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"

[font.bold]
family = "JetBrainsMono Nerd Font"
style = "Bold"

[font.italic]
family = "JetBrainsMono Nerd Font"
style = "Italic"

[font.bold_italic]
family = "JetBrainsMono Nerd Font"
style = "Bold Italic"

[selection]
# save_to_clipboard = true

[colors.primary]
# Catppuccin Mocha
# background = "#1e1e2e"
# foreground = "#cdd6f4"

# Gruvbox Cream-White
background = '#fbf1c7'
foreground = '#3c3836'

[colors.cursor]
# Dark Mode
# text = "#1e1e2e"
# cursor = "#f5e0dc"

# White Mode
cursor = '#3c3836' # dark charcoal
text = '#fbf1c7' # cream

[colors.normal]
black = '#fbf1c7'
red = '#cc241d'
green = '#98971a'
yellow = '#d79921'
blue = '#458588'
magenta = '#b16286'
cyan = '#689d6a'
white = '#7c6f64'

[colors.bright]
black = '#928374'
red = '#9d0006'
green = '#79740e'
yellow = '#b57614'
blue = '#076678'
magenta = '#8f3f71'
cyan = '#427b58'
white = '#3c3836'
